# This is a basic workflow to help you get started with Actions

name: CI for golang

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup golang environment
        uses: actions/setup-go@v2.1.3
        with:
          go-version: '1.15'

      - name: Run tests
        # 执行go程序时一定要先cd到程序所在目录再执行go run 或者 go test
        run: |
          cd ./test/go_run
          go run golang_case.go

          cd ../go_test
          go test -v
